import = ["/home/satou/.config/alacritty/default.toml"]
live_config_reload = false

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "terminuss"
style = "Regular"

[font.bold]
family = "terminuss"
style = "Bold"

[font.italic]
family = "terminuss"
style = "Italic"

[font.bold_italic]
family = "terminuss"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/bin/zsh"

[window.dimensions]
columns = 82
lines = 20

[window.padding]
x = 20
y = 15
